import turtle

turtle.title('Word Turtle Program')
text = turtle.textinput("Turtle.Word", "Введите слово:")
turtle.penup()
turtle.hideturtle()
text_counter = len(text)
width = 100 * 2 + text_counter * 50 + (text_counter - 1) * 10
height = 300
turtle.screensize(width, height)
turtle.setup(width=width,height=height,startx=(-1000 // 2 + 100),starty=(height // 2 - 50))
for i in text:
    if i == 'h':
        turtle.pendown()
        turtle.begin_fill()
        turtle.left(90)
        turtle.forward(50)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(100)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(40)
        turtle.left(90)
        turtle.forward(30)
        turtle.left(90)
        turtle.forward(40)
        turtle.right(90)
        turtle.forward(20)
        turtle.right(90)
        turtle.forward(50)
        turtle.end_fill()
        turtle.penup()
turtle.exitonclick()